require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara
AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "lib/**/*"
    - "config/environments/*"

Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
